# Generated by Django 4.2.9 on 2024-01-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_seen_price',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
