# Generated by Django 4.2.9 on 2024-01-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_product_last_seen_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='putrack',
            name='price_quoted',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
